### ISSUE TITLE
TTL Validation Questions

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#111]
We recently updated the Argus API such that if users don't submit a TTL with an item, that item would simply not expire. Because of this change, I dropped a configuration option Argus had (`defaultTTL`) as it no longer made sense to have it. 

Similarly, `maxTTL` is a configuration option which serves as the maximum TTL users can specify for an item. Does it still make sense to keep this option?  

For context, TTL user input values are represented in seconds.

**Comment by kristinaspring** [comment]
I don't think we need `maxTTL` anymore, if no value means no expiry.

**Comment by JC000** [comment]
Is "permanent storage" a feature we really want to support?  Remember this means we need to migrate data from a persistent DB when we "upgrade".  Also has implications of needing DB backups.  Where as the previous social contract implies we're a cache.  If something went wrong, "Meh.  Oh well.  Upload it again.".

**Comment by schmidtw** [comment]
@JC000 it looks like you introduced the "never expire" concept in this doc change: https://github.com/xmidt-org/argus/compare/main...JC000:update/rest-changes#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R48

I agree with your [comment](https://github.com/xmidt-org/argus/issues/111#issuecomment-767065713) that we don't really want to loose the TTL as a core feature for argus.  Instead of defaulting to never expiring, I think the default for a non-present TTL should be `maxTTL` and not `0`.  An explicit `0` should immediately expire the record.

**Comment by joe94** [comment]
Defaulting the TTL to `maxTTL` when it's not provided by the user makes sense to me. When provided, I think the TTL seconds should be > 0.

**Comment by joe94** [comment]
For `maxTTL`, I believe the default value we have is 1 year. Does that sound still reasonable? 
https://github.com/xmidt-org/argus/blob/main/store/provide.go#L67

**Comment by JC000** [comment]
I don't remember why I added that concept, but we should differentiate the ability to "perma-store" in code, versus the operational flexibility to discard records.  Locking in code behavior as propose would prevent the latter.
