### ISSUE TITLE
Make listener configuration section more explicit to avoid confusing

### ISSUE THREAD

**Issue by joe94** [xmidt-org/argus#139]
While configuring a service using [ancla](https://github.com/xmidt-org/ancla), I found it that the current configuration layout for [argus](https://github.com/xmidt-org/argus/blob/5e7c849d265dcef30ced6cfa3c0e31629036eca3/chrysom/client.go#L89) makes it a bit difficult to distinguish which fields are used to configure the client listener specifically.

For example, ancla defines the [bucket](https://github.com/xmidt-org/ancla/blob/790a102ca6e6b9a19d2070c98ebb153358e3478b/service.go#L64) that will be used as input to argus client calls. Argus then also defines a [bucket](https://github.com/xmidt-org/argus/blob/5e7c849d265dcef30ced6cfa3c0e31629036eca3/chrysom/client.go#L116) that is used for calls made by the listener only.

A couple of options:

- Fix the bucket used for all operations for a given client: the advantage is that it's clear what bucket is used between the listener and the regular client operations. The downside is that it makes the client inflexible in that a new client needs to be created per new bucket.

- Add an explicit listener configuration section the argus client config so that the ancla config would look something like:
```
webhook:
  bucket: "webhooks"
  argus:
    address: http://argus:6300
    listenerConfig:
      bucket: "webhooks"
```

**Comment by kristinaspring** [comment]
I think in most (if not all) cases we would want the argus client to be using the same bucket as ancla. Because the ancla config contains the argus client config, my preference would be removing `Bucket` from the ancla `Config` struct and extracting the bucket information when creating the ancla `Service`.

If we eventually need something more complex, where a service is using multiple buckets at a time, we would likely need separate argus clients (in order to have separate listeners) or other kind of code changes.  Another possibility is only needing ancla for one of those buckets.  I think trying to future proof for these possibilities is too difficult.

There's no current reason why we would wants different buckets, right?

**Comment by joe94** [comment]
Yeah, no reason for ancla's use case. I'm good with that. We can figure something out different use cases come later. So, I will drop the bucket from Ancla's config and leave that as part of the argus config. I'll also modify the argus client method signatures to no longer take a bucket.
