### ISSUE TITLE
Bucket not found error

### ISSUE THREAD

**Issue by utsavbatra5** [xmidt-org/argus#169]
Hi, While posting hook from tr1d1um to argus v0.3.13, we are getting bucket not found error. It works fine on v0.3.11. Can you please advise why it is happening?

**Comment by joe94** [comment]
@utsavbatra5, was this the latest version of Tr1d1um?

**Comment by utsavbatra5** [comment]
@joe94 Its v0.5.5 for Tr1d1um.

**Comment by Sachin4403** [comment]
Hi @joe94 

The issue is only with inmem DB as of now. 

Here is the issue
https://github.com/xmidt-org/argus/blob/d54494d7d33b42f8e19758afd58fc5d4b67200a0/store/inmem/InMem.go#L56-L59
Here we are returning an error (Bucket not found) and here it is not handled.
https://github.com/xmidt-org/argus/blob/d54494d7d33b42f8e19758afd58fc5d4b67200a0/store/endpoint.go#L80-L89

Fix of this issue will be either remove bucket check from inmem DB or  code changes in endpooint.go like below.
```
	if errors.Is(err, ErrItemNotFound) || errors.Is(err, ErrBucketNotFound) 
```

**Comment by joe94** [comment]
Ah, good catch 👍  I don't think the `ErrBucketNotFound` is a very helpful/actionable error TBH. 
I'll remove it and keep the `ErrItemNotFound` only.

**Comment by Sachin4403** [comment]
Do you want us to fix this in issue in otel PR which is opened today by Utsav or you will be fixing this in another  PR?

**Comment by joe94** [comment]
I'll fix it in its own PR 👍
