### ISSUE TITLE
Incomplete log error message

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#237]
Here is a log snippet for submitting a token too early to argus:

> {"level":"error","ts":"2022-07-25T17:55:52Z","msg":"No log message found","requestHeaders":{"Accept-Encoding":["gzip"],"Authorization-Type":["Bearer"],"User-Agent":["Go-http-client/1.1"]},"requestURL":"/api/v1/store/webhooks","method":"GET","error":"failed to parse and validate token: failed to parse JWS: Token is not valid yet","auth":"Bearer [edited]"}

1) The log has msg field: "No log message found"
2) The argus logs in general are different from our other servers and are missing fields, for instance the "code" field e.g. 
`"code":504`.  This makes it more difficult for consistent searching in kibana/building charts that we use internally.

**Comment by ilawjr** [comment]
This may be related: https://github.com/xmidt-org/argus/issues/153

**Comment by denopink** [comment]
Gonna look into this after taking care this round of tr1d1um/webpa-common work

**Comment by denopink** [comment]
Gonna assign to @maurafortino since it may be a good first issue

**Comment by maurafortino** [comment]
3/22  - discussed with Ivan the changes that needed to be made in log statement

1. keyword `level` should be changed to keyword `key`
2. keyword `msg` should be changed to keyword `message` 

this will allow for consistency in log statements across servers which will help with elasticsearch analytics

3/23 - @ilawjr tried to replicate the issue but received the following response:
`{"level":"error","ts":"2006-10-02T18:00:43Z","msg":"failed to parse and validate token: failed to parse JWS: Token is not valid yet","request.Headers":{"Accept-Encoding":["gzip"],"Authorization-Type":["Bearer"],"Traceparent":["00-64cfa32e06ec026dd4f9d7bb4e5fa78c-8069d1e0918c6cbf-00"],"User-Agent":["Go-http-client/1.1"]},"request.URL":"/api/v1/store/webhooks","request.Method":"GET","request.address":"2001:558:fd00:6800:872e:3c9f:56ce:8465","request.path":"/api/v1/store/webhooks","request.query":"","request.tid":"ImH8o3XmU1byumdTkaBBzA","auth":"<token was here>"}`

Due to this - will be closing the issue, but will still address the changes for keywords discussed on 3/22
