### ISSUE TITLE
argus returns unfiltered errors from underlying db

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/argus#30]
Argus directly returns raw errors from the underlying db.  Our test configuration uses dynamodb.  One testcase submitted a 512 deep nested object which exceeded dynamodb's 32 deep limit.  The error header returned was:
``
X-Xmidt-Error: Request Failed:  "ValidationException: Nesting Levels have exceeded supported limits: Attributes in the item have nested levels beyond supported limit\n\tstatus code: 400, request id: [redacted]"
``
We probably shouldn't return the error messages directly as we could accidentally expose important information from the underlying db (security) or other sensitive information. We would be relying on the underlying db to filter its error messages.

**Comment by johnabass** [comment]
This is definitely an example of an error we shouldn't return verbatim, for all the reasons @ilawjr mentions.  A simple `X-Midt-Error` header indicating a database error should suffice.  Details can be logged.

Given that this particular case seems to be a data input issue, it would be better to validate the input first and return a non-database validation error.  The real issue is that we received a deeply nested object that we don't support.

**Comment by joe94** [comment]
Okay, we can add a change to return a DB error and log the actual dynamodb error with the details. 

As for validating the input, we'd essentially need to write a validator that ensures that the JSON depth doesn't go beyond a configurable depth, right?

**Comment by joe94** [comment]
For this issue, we should focus on returning a more generic DB error and only log the specific dynamodb error.

**Comment by joe94** [comment]
As Kristina shared in https://github.com/xmidt-org/argus/issues/29#issuecomment-788239950, we can identify some dynamoDB errors that should result in a 400 BadRequest in Argus. 

Although the way to do it is suboptimal because of the dynamoDB Go SDK, we can accomplish the above by:
- Filtering errors https://docs.aws.amazon.com/sdk-for-go/api/aws/awserr/#Error whose Code matches `ErrCodeTransactionCanceledException` 
- Out of those filtered errors, we'd be interested in capturing the ones whose `Message()` function returns a string that starts with `ValidationException`
